define([
    './main',
    './accountEditController',
    './accountListController',
    './accountNewController',
    './adminBarController',
    './authorizationController',
    './documentShowController',
    './documentListController',
    './documentNewController',
    './footerController',
    './homeController',
    './pubmedProviderController',
    './searchController',
    './searchResultsController',
], function( ) { });
