language: scala
scala:
  - 2.10.4
jdk:
  - oraclejdk8
  - openjdk8
  - oraclejdk7
  - openjdk7
before_script:
  - tar -C src/main/resources --lzma -xvf src/main/resources/linnaeus.tar.lzma
  - tar -C src/main/resources --lzma -xvf src/main/resources/abner.tar.lzma
notifications:
  email:
    - agjacome@gmail.com
