language: scala
scala:
  - 2.11.7
jdk:
  - oraclejdk8
before_script:
  - tar -C share/ --lzma -xvf share/linnaeus.tar.lzma
notifications:
  email:
    recipients:
      - agjacome@esei.uvigo.es
    on_success: change
    on_failure: always
    on_start: false
